### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by Tyrell20** [alikhairi/fireeye-miner#1]
Hello,
We are facing an issue about the polling from the miner.
We have the error below:
`string indices must be integers`

We have installed and configure the miner without any error.

Many thanks for your help.

**Comment by alikhairi** [comment]
Did you still got the error. Im being using this extension without an issue so far.

**Comment by Tyrell20** [comment]
Yes unfortunately it is still present.
The error shows strings below:

`2022-01-11T14:03:18 (2669)basepoller._poll ERROR: Exception in polling loop for FireEye_iSIGHT: string indices must be integers
Traceback (most recent call last):
File "/opt/minemeld/engine/core/minemeld/ft/basepoller.py", line 737, in _poll
performed = self._polling_loop()
File "/opt/minemeld/engine/core/minemeld/ft/basepoller.py", line 584, in _polling_loop
iterator = self._build_iterator(now)
File "/opt/minemeld/local/library/22243484-8f88-4887-b367-d5065213b9ba/fireeyeminer/node.py", line 69, in _build_iterator
if message[indicator]:
TypeError: string indices must be integers`
